| test loss  3.49 | test ppl    32.66
-----------------------------------------------------------------------------------------
| epoch   6 |  2000/49593 batches | lr 0.00020 | ms/batch 157.97 | loss  3.46 | ppl    31.96
/opt/conda/conda-bld/pytorch_1518241081361/work/torch/lib/THC/THCTensorIndex.cu:417: long calculateOffset(IndexType, LinearIndexCalcData<IndexType, Dims>) [with IndexType = unsigned int, Dims = 3U]: block: [283,0,0], thread: [136,0,0] Assertion `indexAtDim < data.baseSizes[dim]` failed.
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1518241081361/work/torch/lib/THC/generic/THCTensorIndex.cu line=767 error=59 : device-side assert triggered
Traceback (most recent call last):
  File "main.py", line 57, in <module>
    run(args)
  File "main.py", line 44, in run
    n_layers, hidden_size, print_every)
  File "/home/jianmo/research/expansionNet/final-code/lexicon-title-expansion/train.py", line 256, in trainIters
    loss = train(attr_input, summary_input, summary_input_lengths, title_input, title_input_lengths, target_variable, mask, max_target_len, encoder1, encoder2, encoder3, decoder, embedding, encoder1_optimizer, encoder2_optimizer, encoder3_optimizer, decoder_optimizer, batch_size)
  File "/home/jianmo/research/expansionNet/final-code/lexicon-title-expansion/train.py", line 73, in train
    loss.backward()
  File "/home/jianmo/anaconda2/envs/venv35/lib/python3.5/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/jianmo/anaconda2/envs/venv35/lib/python3.5/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
  File "/home/jianmo/anaconda2/envs/venv35/lib/python3.5/site-packages/torch/autograd/function.py", line 91, in apply
    return self._forward_cls.backward(self, *args)
  File "/home/jianmo/anaconda2/envs/venv35/lib/python3.5/site-packages/torch/autograd/_functions/tensor.py", line 98, in backward
    grad_input._advanced_index_add(ctx.index, grad_output)
  File "/home/jianmo/anaconda2/envs/venv35/lib/python3.5/site-packages/torch/autograd/variable.py", line 404, in _advanced_index_add
    return AdvancedIndexAdd.apply(self, index, tensor)
  File "/home/jianmo/anaconda2/envs/venv35/lib/python3.5/site-packages/torch/autograd/_functions/tensor.py", line 253, in forward
    return tensor1._advanced_index_add(index, tensor2)
RuntimeError: cuda runtime error (59) : device-side assert triggered at /opt/conda/conda-bld/pytorch_1518241081361/work/torch/lib/THC/generic/THCTensorIndex.cu:767
